// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (id, user_id, code, created_at, expires_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    $3
)
RETURNING id, user_id, code, created_at, expires_at
`

type CreateEmailVerificationParams struct {
	UserID    uuid.UUID
	Code      int32
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerification, arg.UserID, arg.Code, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
