// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailVerification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	UserEmail string
	Code      string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Genre struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Movie struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

type MovieGenre struct {
	MovieID   uuid.UUID
	GenreID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PwResetToken struct {
	HashedToken string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Reservation struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ScreeningID uuid.UUID
	RoomID      uuid.UUID
	SeatID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Room struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Screening struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Seat struct {
	ID         uuid.UUID
	RoomID     uuid.UUID
	RowLabel   string
	SeatNumber int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Role           string
	IsActive       bool
}
