// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (id, created_at, updated_at, name)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, createGenre, name)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url
`

type CreateMovieParams struct {
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.RuntimeMinutes,
		arg.ReleaseDate,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const getMovieBySlug = `-- name: GetMovieBySlug :one
SELECT id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url FROM movies
WHERE slug = $1
`

func (q *Queries) GetMovieBySlug(ctx context.Context, slug string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieBySlug, slug)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const getMoviesByGenre = `-- name: GetMoviesByGenre :many
SELECT DISTINCT m.id, m.created_at, m.updated_at, m.title, m.slug, m.description, m.runtime_minutes, m.release_date, m.poster_url
FROM movies m
INNER JOIN movie_genre mg ON m.id = mg.movie_id
INNER JOIN genres g ON mg.genre_id = g.id
WHERE g.id = $1
ORDER BY m.created_at DESC
`

func (q *Queries) GetMoviesByGenre(ctx context.Context, id uuid.UUID) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, getMoviesByGenre, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.RuntimeMinutes,
			&i.ReleaseDate,
			&i.PosterUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title = $2, slug = $3, description = $4, runtime_minutes = $5, release_date = $6, poster_url = $7
WHERE id = $1
RETURNING id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url
`

type UpdateMovieParams struct {
	ID             uuid.UUID
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.RuntimeMinutes,
		arg.ReleaseDate,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}
