// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignGenresToMovie = `-- name: AssignGenresToMovie :exec
INSERT INTO movie_genre (movie_id, genre_id, created_at, updated_at)
VALUES (
    $1,
    unnest($2::uuid[]),
    NOW(),
    NOW()
)
`

type AssignGenresToMovieParams struct {
	MovieID  uuid.UUID
	GenreIds []uuid.UUID
}

func (q *Queries) AssignGenresToMovie(ctx context.Context, arg AssignGenresToMovieParams) error {
	_, err := q.db.ExecContext(ctx, assignGenresToMovie, arg.MovieID, pq.Array(arg.GenreIds))
	return err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url
`

type CreateMovieParams struct {
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.RuntimeMinutes,
		arg.ReleaseDate,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const deleteMovieGenres = `-- name: DeleteMovieGenres :exec
DELETE FROM movie_genre
WHERE movie_id = $1
`

func (q *Queries) DeleteMovieGenres(ctx context.Context, movieID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovieGenres, movieID)
	return err
}

const getCurrentMoviesSummary = `-- name: GetCurrentMoviesSummary :many
SELECT
    m.id, m.title, m.slug, m.poster_url
FROM movies m
JOIN screenings s ON s.movie_id = m.id
WHERE s.start_time >= NOW()
GROUP BY m.id
ORDER BY m.title ASC
`

type GetCurrentMoviesSummaryRow struct {
	ID        uuid.UUID
	Title     string
	Slug      string
	PosterUrl sql.NullString
}

func (q *Queries) GetCurrentMoviesSummary(ctx context.Context) ([]GetCurrentMoviesSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentMoviesSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentMoviesSummaryRow
	for rows.Next() {
		var i GetCurrentMoviesSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PosterUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieDetailByID = `-- name: GetMovieDetailByID :one
SELECT
    m.id, m.created_at, m.updated_at, m.title, m.slug, m.description, m.runtime_minutes, m.release_date, m.poster_url,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'id',           g.id,
                'created_at',   g.created_at,
                'updated_at',   g.updated_at,
                'name',         g.name
            )
        ) FILTER (WHERE g.id IS NOT NULL),
        '[]'
    ) AS genres
FROM movies m
LEFT JOIN movie_genre mg ON m.id = mg.movie_id
LEFT JOIN genres       g ON mg.genre_id = g.id
WHERE m.id = $1
GROUP BY m.id
`

type GetMovieDetailByIDRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
	Genres         interface{}
}

func (q *Queries) GetMovieDetailByID(ctx context.Context, id uuid.UUID) (GetMovieDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMovieDetailByID, id)
	var i GetMovieDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
		&i.Genres,
	)
	return i, err
}

const getMoviesSummary = `-- name: GetMoviesSummary :many
SELECT
    m.id, m.title, m.slug, m.poster_url
FROM movies m
LEFT JOIN movie_genre mg ON m.id = mg.movie_id
WHERE ($1::uuid IS NULL OR mg.genre_id = $1)
    AND ($2::text IS NULL OR m.title ILIKE '%' || $2 || '%')
    AND ($3::date IS NULL OR m.release_date >= $3::date)
    AND ($4::date IS NULL OR m.release_date <= $4::date)
    AND ($5::int IS NULL OR m.runtime_minutes >= $5::int)
    AND ($6::int IS NULL OR m.runtime_minutes <= $6::int)
GROUP BY m.id
ORDER BY m.title ASC
LIMIT $8
OFFSET $7
`

type GetMoviesSummaryParams struct {
	GenreID         uuid.NullUUID
	Title           sql.NullString
	ReleaseDateFrom sql.NullTime
	ReleaseDateTo   sql.NullTime
	RuntimeMin      sql.NullInt32
	RuntimeMax      sql.NullInt32
	Offset          int32
	Limit           int32
}

type GetMoviesSummaryRow struct {
	ID        uuid.UUID
	Title     string
	Slug      string
	PosterUrl sql.NullString
}

func (q *Queries) GetMoviesSummary(ctx context.Context, arg GetMoviesSummaryParams) ([]GetMoviesSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getMoviesSummary,
		arg.GenreID,
		arg.Title,
		arg.ReleaseDateFrom,
		arg.ReleaseDateTo,
		arg.RuntimeMin,
		arg.RuntimeMax,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesSummaryRow
	for rows.Next() {
		var i GetMoviesSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PosterUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET updated_at = NOW(), title = $2, slug = $3, description = $4, runtime_minutes = $5, release_date = $6, poster_url = $7
WHERE id = $1
RETURNING id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url
`

type UpdateMovieParams struct {
	ID             uuid.UUID
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.RuntimeMinutes,
		arg.ReleaseDate,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const uploadMoviePoster = `-- name: UploadMoviePoster :exec
UPDATE movies
SET poster_url = $2, updated_at = NOW()
WHERE id = $1
`

type UploadMoviePosterParams struct {
	ID        uuid.UUID
	PosterUrl sql.NullString
}

func (q *Queries) UploadMoviePoster(ctx context.Context, arg UploadMoviePosterParams) error {
	_, err := q.db.ExecContext(ctx, uploadMoviePoster, arg.ID, arg.PosterUrl)
	return err
}
