// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignGenresToMovie = `-- name: AssignGenresToMovie :exec
INSERT INTO movie_genre (movie_id, genre_id, created_at, updated_at)
SELECT $1, unnest($2::uuid[]), NOW(), NOW()
ON CONFLICT DO NOTHING
`

type AssignGenresToMovieParams struct {
	MovieID uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) AssignGenresToMovie(ctx context.Context, arg AssignGenresToMovieParams) error {
	_, err := q.db.ExecContext(ctx, assignGenresToMovie, arg.MovieID, pq.Array(arg.Column2))
	return err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url
`

type CreateMovieParams struct {
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.RuntimeMinutes,
		arg.ReleaseDate,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const deleteMovieGenres = `-- name: DeleteMovieGenres :exec
DELETE FROM movie_genre
WHERE movie_id = $1
`

func (q *Queries) DeleteMovieGenres(ctx context.Context, movieID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovieGenres, movieID)
	return err
}

const getMovieByID = `-- name: GetMovieByID :one
SELECT id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url FROM movies
WHERE id = $1
`

func (q *Queries) GetMovieByID(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieByID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const getMovieBySlug = `-- name: GetMovieBySlug :one
SELECT id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url FROM movies
WHERE slug = $1
`

func (q *Queries) GetMovieBySlug(ctx context.Context, slug string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieBySlug, slug)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}

const getMoviesByGenre = `-- name: GetMoviesByGenre :many
SELECT DISTINCT m.id, m.created_at, m.updated_at, m.title, m.slug, m.description, m.runtime_minutes, m.release_date, m.poster_url
FROM movies m
INNER JOIN movie_genre mg ON m.id = mg.movie_id
INNER JOIN genres g ON mg.genre_id = g.id
WHERE g.id = $1
ORDER BY m.created_at DESC
`

func (q *Queries) GetMoviesByGenre(ctx context.Context, id uuid.UUID) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, getMoviesByGenre, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.RuntimeMinutes,
			&i.ReleaseDate,
			&i.PosterUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET updated_at = NOW(), title = $2, slug = $3, description = $4, runtime_minutes = $5, release_date = $6, poster_url = $7
WHERE id = $1
RETURNING id, created_at, updated_at, title, slug, description, runtime_minutes, release_date, poster_url
`

type UpdateMovieParams struct {
	ID             uuid.UUID
	Title          string
	Slug           string
	Description    sql.NullString
	RuntimeMinutes sql.NullInt32
	ReleaseDate    sql.NullTime
	PosterUrl      sql.NullString
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.RuntimeMinutes,
		arg.ReleaseDate,
		arg.PosterUrl,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.RuntimeMinutes,
		&i.ReleaseDate,
		&i.PosterUrl,
	)
	return i, err
}
