// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pw_reset_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO pw_reset_tokens (hashed_token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING hashed_token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreatePasswordResetTokenParams struct {
	HashedToken string
	UserID      uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PwResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.HashedToken, arg.UserID, arg.ExpiresAt)
	var i PwResetToken
	err := row.Scan(
		&i.HashedToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT hashed_token, created_at, updated_at, user_id, expires_at, revoked_at
FROM pw_reset_tokens
WHERE hashed_token = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, hashedToken string) (PwResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, hashedToken)
	var i PwResetToken
	err := row.Scan(
		&i.HashedToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokePasswordResetToken = `-- name: RevokePasswordResetToken :exec
UPDATE pw_reset_tokens
SET updated_at = NOW(), revoked_at = NOW()
WHERE hashed_token = $1
`

func (q *Queries) RevokePasswordResetToken(ctx context.Context, hashedToken string) error {
	_, err := q.db.ExecContext(ctx, revokePasswordResetToken, hashedToken)
	return err
}
