// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (id, created_at, updated_at, user_id, screening_id, room_id, seat_id)
SELECT
    gen_random_uuid(), 
    NOW(), 
    NOW(),
    $1,
    $2,
    s.room_id,
    $3
FROM screenings s
WHERE s.id = $2
RETURNING id, user_id, screening_id, room_id, seat_id, created_at, updated_at
`

type CreateReservationParams struct {
	UserID      uuid.UUID
	ScreeningID uuid.UUID
	SeatID      uuid.UUID
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation, arg.UserID, arg.ScreeningID, arg.SeatID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScreeningID,
		&i.RoomID,
		&i.SeatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations
WHERE id = $1
`

func (q *Queries) DeleteReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReservation, id)
	return err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, user_id, screening_id, room_id, seat_id, created_at, updated_at FROM reservations 
WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScreeningID,
		&i.RoomID,
		&i.SeatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservations = `-- name: GetReservations :many
SELECT r.id, r.user_id, r.screening_id, r.room_id, r.seat_id, r.created_at, r.updated_at FROM reservations r
JOIN screenings s ON r.screening_id = s.id
WHERE ($1::uuid IS NULL OR r.user_id = $1)
  AND ($2::uuid IS NULL OR r.screening_id = $2)
  AND ($3::uuid IS NULL OR s.movie_id = $3)
  AND ($4::uuid IS NULL OR r.room_id = $4)
ORDER BY r.created_at DESC
LIMIT $6
OFFSET $5
`

type GetReservationsParams struct {
	UserID      uuid.NullUUID
	ScreeningID uuid.NullUUID
	MovieID     uuid.NullUUID
	RoomID      uuid.NullUUID
	Offset      int32
	Limit       int32
}

func (q *Queries) GetReservations(ctx context.Context, arg GetReservationsParams) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getReservations,
		arg.UserID,
		arg.ScreeningID,
		arg.MovieID,
		arg.RoomID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScreeningID,
			&i.RoomID,
			&i.SeatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationsByUserID = `-- name: GetReservationsByUserID :many
SELECT id, user_id, screening_id, room_id, seat_id, created_at, updated_at FROM reservations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReservationsByUserID(ctx context.Context, userID uuid.UUID) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getReservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScreeningID,
			&i.RoomID,
			&i.SeatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservation = `-- name: UpdateReservation :one
UPDATE reservations
SET updated_at = NOW(), user_id = $2, screening_id = $3, room_id = s.room_id, seat_id = $4
FROM screenings s
WHERE reservations.id = $1
  AND s.id = $3
RETURNING reservations.id, reservations.user_id, reservations.screening_id, reservations.room_id, reservations.seat_id, reservations.created_at, reservations.updated_at
`

type UpdateReservationParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ScreeningID uuid.UUID
	SeatID      uuid.UUID
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, updateReservation,
		arg.ID,
		arg.UserID,
		arg.ScreeningID,
		arg.SeatID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScreeningID,
		&i.RoomID,
		&i.SeatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
