// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (id, created_at, updated_at, user_id, screening_id, room_id, seat_id)
SELECT
    gen_random_uuid(), 
    NOW(), 
    NOW(),
    $1,
    $2,
    s.room_id,
    $3
FROM screenings s
WHERE s.id = $2
RETURNING id, user_id, screening_id, room_id, seat_id, created_at, updated_at
`

type CreateReservationParams struct {
	UserID      uuid.UUID
	ScreeningID uuid.UUID
	SeatID      uuid.UUID
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation, arg.UserID, arg.ScreeningID, arg.SeatID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScreeningID,
		&i.RoomID,
		&i.SeatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations
WHERE id = $1
`

func (q *Queries) DeleteReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReservation, id)
	return err
}

const getReservationDetailByID = `-- name: GetReservationDetailByID :one
SELECT 
r.id, 
r.created_at,
r.updated_at,
u.id AS user_id,
u.email AS user_email,
sc.id AS screening_id, 
sc.start_time AS screening_start_time, 
sc.end_time AS screening_end_time,  
m.id AS movie_id,
m.title AS movie_title,
m.slug AS movie_slug,
m.poster_url AS movie_poster_url,
rm.id AS room_id,
rm.name AS room_name,
s.id AS seat_id,
s.row_label AS seat_row_label,
s.seat_number AS seat_number
FROM reservations r
JOIN screenings sc ON r.screening_id = sc.id
JOIN movies m ON sc.movie_id = m.id
JOIN seats s ON r.seat_id = s.id
JOIN users u ON r.user_id = u.id
JOIN rooms rm ON r.room_id = rm.id
WHERE r.id = $1
`

type GetReservationDetailByIDRow struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	UserID             uuid.UUID
	UserEmail          string
	ScreeningID        uuid.UUID
	ScreeningStartTime time.Time
	ScreeningEndTime   time.Time
	MovieID            uuid.UUID
	MovieTitle         string
	MovieSlug          string
	MoviePosterUrl     sql.NullString
	RoomID             uuid.UUID
	RoomName           string
	SeatID             uuid.UUID
	SeatRowLabel       string
	SeatNumber         int32
}

func (q *Queries) GetReservationDetailByID(ctx context.Context, id uuid.UUID) (GetReservationDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReservationDetailByID, id)
	var i GetReservationDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.ScreeningID,
		&i.ScreeningStartTime,
		&i.ScreeningEndTime,
		&i.MovieID,
		&i.MovieTitle,
		&i.MovieSlug,
		&i.MoviePosterUrl,
		&i.RoomID,
		&i.RoomName,
		&i.SeatID,
		&i.SeatRowLabel,
		&i.SeatNumber,
	)
	return i, err
}

const getReservationMetaByID = `-- name: GetReservationMetaByID :one
SELECT r.id, r.user_id, r.screening_id, r.room_id, r.seat_id, r.created_at, r.updated_at, sc.start_time AS screening_start_time
FROM reservations r
JOIN screenings sc ON r.screening_id = sc.id
WHERE r.id = $1
`

type GetReservationMetaByIDRow struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ScreeningID        uuid.UUID
	RoomID             uuid.UUID
	SeatID             uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ScreeningStartTime time.Time
}

func (q *Queries) GetReservationMetaByID(ctx context.Context, id uuid.UUID) (GetReservationMetaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReservationMetaByID, id)
	var i GetReservationMetaByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScreeningID,
		&i.RoomID,
		&i.SeatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScreeningStartTime,
	)
	return i, err
}

const getReservationsSummary = `-- name: GetReservationsSummary :many
SELECT 
r.id, 
sc.id AS screening_id, 
sc.start_time AS screening_start_time, 
sc.end_time AS screening_end_time,  
m.id AS movie_id,
m.title AS movie_title,
m.slug AS movie_slug,
m.poster_url AS movie_poster_url,
s.id AS seat_id,
s.row_label AS seat_row_label,
s.seat_number AS seat_number
FROM reservations r
JOIN screenings sc ON r.screening_id = sc.id
JOIN movies m ON sc.movie_id = m.id
JOIN seats s ON r.seat_id = s.id
WHERE ($1::uuid IS NULL OR r.user_id = $1)
  AND ($2::uuid IS NULL OR r.screening_id = $2)
  AND ($3::uuid IS NULL OR sc.movie_id = $3)
  AND ($4::uuid IS NULL OR r.room_id = $4)
ORDER BY r.created_at DESC
LIMIT $6
OFFSET $5
`

type GetReservationsSummaryParams struct {
	UserID      uuid.NullUUID
	ScreeningID uuid.NullUUID
	MovieID     uuid.NullUUID
	RoomID      uuid.NullUUID
	Offset      int32
	Limit       int32
}

type GetReservationsSummaryRow struct {
	ID                 uuid.UUID
	ScreeningID        uuid.UUID
	ScreeningStartTime time.Time
	ScreeningEndTime   time.Time
	MovieID            uuid.UUID
	MovieTitle         string
	MovieSlug          string
	MoviePosterUrl     sql.NullString
	SeatID             uuid.UUID
	SeatRowLabel       string
	SeatNumber         int32
}

func (q *Queries) GetReservationsSummary(ctx context.Context, arg GetReservationsSummaryParams) ([]GetReservationsSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getReservationsSummary,
		arg.UserID,
		arg.ScreeningID,
		arg.MovieID,
		arg.RoomID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservationsSummaryRow
	for rows.Next() {
		var i GetReservationsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.ScreeningID,
			&i.ScreeningStartTime,
			&i.ScreeningEndTime,
			&i.MovieID,
			&i.MovieTitle,
			&i.MovieSlug,
			&i.MoviePosterUrl,
			&i.SeatID,
			&i.SeatRowLabel,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
