// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, created_at, updated_at, name)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateRoom(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoomDetailByID = `-- name: GetRoomDetailByID :one
SELECT
    r.id, r.name, r.created_at, r.updated_at,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'id',           s.id,
                'room_id',      s.room_id,
                'row_label',    s.row_label,
                'seat_number',  s.seat_number,
                'created_at',   s.created_at,
                'updated_at',   s.updated_at
            )
        ) FILTER (WHERE s.id IS NOT NULL),
        '[]'
    ) AS seats
FROM rooms r
LEFT JOIN seats s ON r.id = s.room_id
WHERE r.id = $1
GROUP BY r.id
`

type GetRoomDetailByIDRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Seats     interface{}
}

func (q *Queries) GetRoomDetailByID(ctx context.Context, id uuid.UUID) (GetRoomDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomDetailByID, id)
	var i GetRoomDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Seats,
	)
	return i, err
}

const getRoomsSummary = `-- name: GetRoomsSummary :many
SELECT 
    r.id,
    r.name
FROM rooms r
ORDER BY r.name
`

type GetRoomsSummaryRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetRoomsSummary(ctx context.Context) ([]GetRoomsSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomsSummaryRow
	for rows.Next() {
		var i GetRoomsSummaryRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET updated_at = NOW(), name = $2
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateRoomParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom, arg.ID, arg.Name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
