// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screenings.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createScreening = `-- name: CreateScreening :one
INSERT INTO screenings (id, created_at, updated_at, movie_id, room_id, start_time, end_time)
VALUES (    
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, movie_id, room_id, start_time, end_time, created_at, updated_at
`

type CreateScreeningParams struct {
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) CreateScreening(ctx context.Context, arg CreateScreeningParams) (Screening, error) {
	row := q.db.QueryRowContext(ctx, createScreening,
		arg.MovieID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScreening = `-- name: DeleteScreening :exec
DELETE FROM screenings
WHERE id = $1
`

func (q *Queries) DeleteScreening(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteScreening, id)
	return err
}

const getScreeningDetailByID = `-- name: GetScreeningDetailByID :one
SELECT 
    sc.id,
    sc.start_time,
    sc.end_time,
    sc.created_at,
    sc.updated_at,
    sc.movie_id,
    m.title         AS movie_title,
    m.slug          AS movie_slug,
    m.poster_url    AS movie_poster_url,
    sc.room_id,
    r.name          AS room_name,
    COALESCE(seats_agg.seats, '[]') AS seats
FROM screenings sc
JOIN rooms r ON sc.room_id = r.id
JOIN movies m ON sc.movie_id = m.id
LEFT JOIN (
    SELECT
        s.room_id,
        jsonb_agg(
            jsonb_build_object(
                'id',          s.id,
                'row_label',   s.row_label,
                'seat_number', s.seat_number,
                'available',   (res.id IS NULL)
            )
        ) AS seats
    FROM seats s
    LEFT JOIN reservations res 
        ON s.id = res.seat_id 
        AND res.screening_id = $1
    GROUP BY s.room_id
) seats_agg ON r.id = seats_agg.room_id
WHERE sc.id = $1
`

type GetScreeningDetailByIDRow struct {
	ID             uuid.UUID
	StartTime      time.Time
	EndTime        time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MovieID        uuid.UUID
	MovieTitle     string
	MovieSlug      string
	MoviePosterUrl sql.NullString
	RoomID         uuid.UUID
	RoomName       string
	Seats          json.RawMessage
}

func (q *Queries) GetScreeningDetailByID(ctx context.Context, screeningID uuid.UUID) (GetScreeningDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getScreeningDetailByID, screeningID)
	var i GetScreeningDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MovieID,
		&i.MovieTitle,
		&i.MovieSlug,
		&i.MoviePosterUrl,
		&i.RoomID,
		&i.RoomName,
		&i.Seats,
	)
	return i, err
}

const getScreeningsSummary = `-- name: GetScreeningsSummary :many
SELECT sc.id, sc.start_time, sc.end_time,
sc.movie_id,
m.title AS movie_title,
m.slug AS movie_slug,
m.poster_url AS movie_poster_url
FROM screenings sc
JOIN rooms r ON sc.room_id = r.id
JOIN movies m ON sc.movie_id = m.id
WHERE ($1::uuid IS NULL OR sc.movie_id = $1)
  AND ($2::uuid IS NULL OR sc.room_id = $2)
  AND ($3::timestamp IS NULL OR sc.start_time >= $3)
  AND ($4::timestamp IS NULL OR sc.start_time <= $4)
ORDER BY sc.start_time
LIMIT $6
OFFSET $5
`

type GetScreeningsSummaryParams struct {
	MovieID uuid.NullUUID
	RoomID  uuid.NullUUID
	From    sql.NullTime
	To      sql.NullTime
	Offset  int32
	Limit   int32
}

type GetScreeningsSummaryRow struct {
	ID             uuid.UUID
	StartTime      time.Time
	EndTime        time.Time
	MovieID        uuid.UUID
	MovieTitle     string
	MovieSlug      string
	MoviePosterUrl sql.NullString
}

func (q *Queries) GetScreeningsSummary(ctx context.Context, arg GetScreeningsSummaryParams) ([]GetScreeningsSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getScreeningsSummary,
		arg.MovieID,
		arg.RoomID,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScreeningsSummaryRow
	for rows.Next() {
		var i GetScreeningsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.MovieID,
			&i.MovieTitle,
			&i.MovieSlug,
			&i.MoviePosterUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScreening = `-- name: UpdateScreening :one
UPDATE screenings
SET updated_at = NOW(), movie_id = $2, room_id = $3, start_time = $4, end_time = $5
WHERE id = $1
RETURNING id, movie_id, room_id, start_time, end_time, created_at, updated_at
`

type UpdateScreeningParams struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) UpdateScreening(ctx context.Context, arg UpdateScreeningParams) (Screening, error) {
	row := q.db.QueryRowContext(ctx, updateScreening,
		arg.ID,
		arg.MovieID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
