// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screenings.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScreening = `-- name: CreateScreening :one
INSERT INTO screenings (id, created_at, updated_at, movie_id, room_id, start_time, end_time)
VALUES (    
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, movie_id, room_id, start_time, end_time, created_at, updated_at
`

type CreateScreeningParams struct {
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) CreateScreening(ctx context.Context, arg CreateScreeningParams) (Screening, error) {
	row := q.db.QueryRowContext(ctx, createScreening,
		arg.MovieID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScreening = `-- name: DeleteScreening :exec
DELETE FROM screenings
WHERE id = $1
`

func (q *Queries) DeleteScreening(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteScreening, id)
	return err
}

const getScreeningByID = `-- name: GetScreeningByID :one
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE id = $1
`

func (q *Queries) GetScreeningByID(ctx context.Context, id uuid.UUID) (Screening, error) {
	row := q.db.QueryRowContext(ctx, getScreeningByID, id)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScreeningsByDateRange = `-- name: GetScreeningsByDateRange :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE start_time >= $1 AND start_time <= $2
ORDER BY start_time
`

type GetScreeningsByDateRangeParams struct {
	StartTime   time.Time
	StartTime_2 time.Time
}

func (q *Queries) GetScreeningsByDateRange(ctx context.Context, arg GetScreeningsByDateRangeParams) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getScreeningsByDateRange, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScreeningsByMovieID = `-- name: GetScreeningsByMovieID :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE movie_id = $1
ORDER BY start_time
`

func (q *Queries) GetScreeningsByMovieID(ctx context.Context, movieID uuid.UUID) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getScreeningsByMovieID, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScreeningsByMovieIDAndDateRange = `-- name: GetScreeningsByMovieIDAndDateRange :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE movie_id = $1 AND start_time >= $2 AND start_time <= $3
ORDER BY start_time
`

type GetScreeningsByMovieIDAndDateRangeParams struct {
	MovieID     uuid.UUID
	StartTime   time.Time
	StartTime_2 time.Time
}

func (q *Queries) GetScreeningsByMovieIDAndDateRange(ctx context.Context, arg GetScreeningsByMovieIDAndDateRangeParams) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getScreeningsByMovieIDAndDateRange, arg.MovieID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScreeningsPaginated = `-- name: GetScreeningsPaginated :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
ORDER BY start_time
LIMIT $1 OFFSET $2
`

type GetScreeningsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetScreeningsPaginated(ctx context.Context, arg GetScreeningsPaginatedParams) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getScreeningsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingScreeningsByDateRange = `-- name: GetUpcomingScreeningsByDateRange :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE start_time >= NOW() AND start_time >= $1 AND start_time <= $2
ORDER BY start_time
`

type GetUpcomingScreeningsByDateRangeParams struct {
	StartTime   time.Time
	StartTime_2 time.Time
}

func (q *Queries) GetUpcomingScreeningsByDateRange(ctx context.Context, arg GetUpcomingScreeningsByDateRangeParams) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingScreeningsByDateRange, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingScreeningsByMovieID = `-- name: GetUpcomingScreeningsByMovieID :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE movie_id = $1 AND start_time >= NOW()
ORDER BY start_time
`

func (q *Queries) GetUpcomingScreeningsByMovieID(ctx context.Context, movieID uuid.UUID) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingScreeningsByMovieID, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingScreeningsByMovieIDAndDateRange = `-- name: GetUpcomingScreeningsByMovieIDAndDateRange :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE movie_id = $1 AND start_time >= NOW() AND start_time >= $2 AND start_time <= $3
ORDER BY start_time
`

type GetUpcomingScreeningsByMovieIDAndDateRangeParams struct {
	MovieID     uuid.UUID
	StartTime   time.Time
	StartTime_2 time.Time
}

func (q *Queries) GetUpcomingScreeningsByMovieIDAndDateRange(ctx context.Context, arg GetUpcomingScreeningsByMovieIDAndDateRangeParams) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingScreeningsByMovieIDAndDateRange, arg.MovieID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScreening = `-- name: UpdateScreening :one
UPDATE screenings
SET updated_at = NOW(), movie_id = $2, room_id = $3, start_time = $4, end_time = $5
WHERE id = $1
RETURNING id, movie_id, room_id, start_time, end_time, created_at, updated_at
`

type UpdateScreeningParams struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) UpdateScreening(ctx context.Context, arg UpdateScreeningParams) (Screening, error) {
	row := q.db.QueryRowContext(ctx, updateScreening,
		arg.ID,
		arg.MovieID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
