// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: screenings.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScreening = `-- name: CreateScreening :one
INSERT INTO screenings (id, created_at, updated_at, movie_id, room_id, start_time, end_time)
VALUES (    
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, movie_id, room_id, start_time, end_time, created_at, updated_at
`

type CreateScreeningParams struct {
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) CreateScreening(ctx context.Context, arg CreateScreeningParams) (Screening, error) {
	row := q.db.QueryRowContext(ctx, createScreening,
		arg.MovieID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScreening = `-- name: DeleteScreening :exec
DELETE FROM screenings
WHERE id = $1
`

func (q *Queries) DeleteScreening(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteScreening, id)
	return err
}

const getScreeningByID = `-- name: GetScreeningByID :one
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings
WHERE id = $1
`

func (q *Queries) GetScreeningByID(ctx context.Context, id uuid.UUID) (Screening, error) {
	row := q.db.QueryRowContext(ctx, getScreeningByID, id)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScreenings = `-- name: GetScreenings :many
SELECT id, movie_id, room_id, start_time, end_time, created_at, updated_at FROM screenings s
WHERE ($1::uuid IS NULL OR s.movie_id = $1)
  AND ($2::uuid IS NULL OR s.room_id = $2)
  AND ($3::timestampt IS NULL OR s.start_time >= $3)
  AND ($4::timestampt IS NULL OR s.start_time <= $4)
  AND ($5::bool IS FALSE OR s.start_time >= NOW())
ORDER BY start_time
LIMIT $7
OFFSET $6
`

type GetScreeningsParams struct {
	MovieID  uuid.NullUUID
	RoomID   uuid.NullUUID
	From     interface{}
	To       interface{}
	Upcoming bool
	Offset   int32
	Limit    int32
}

func (q *Queries) GetScreenings(ctx context.Context, arg GetScreeningsParams) ([]Screening, error) {
	rows, err := q.db.QueryContext(ctx, getScreenings,
		arg.MovieID,
		arg.RoomID,
		arg.From,
		arg.To,
		arg.Upcoming,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScreening = `-- name: UpdateScreening :one
UPDATE screenings
SET updated_at = NOW(), movie_id = $2, room_id = $3, start_time = $4, end_time = $5
WHERE id = $1
RETURNING id, movie_id, room_id, start_time, end_time, created_at, updated_at
`

type UpdateScreeningParams struct {
	ID        uuid.UUID
	MovieID   uuid.UUID
	RoomID    uuid.UUID
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) UpdateScreening(ctx context.Context, arg UpdateScreeningParams) (Screening, error) {
	row := q.db.QueryRowContext(ctx, updateScreening,
		arg.ID,
		arg.MovieID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
