// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seats.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (id, room_id, row_label, seat_number, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW()
)
RETURNING id, room_id, row_label, seat_number, created_at, updated_at
`

type CreateSeatParams struct {
	RoomID     uuid.UUID
	RowLabel   string
	SeatNumber int32
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRowContext(ctx, createSeat, arg.RoomID, arg.RowLabel, arg.SeatNumber)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RowLabel,
		&i.SeatNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeat = `-- name: DeleteSeat :exec
DELETE FROM seats
WHERE id = $1
`

func (q *Queries) DeleteSeat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSeat, id)
	return err
}

const getSeatDetailByID = `-- name: GetSeatDetailByID :one
SELECT s.id, s.room_id, s.row_label, s.seat_number, s.created_at, s.updated_at, r.name AS room_name FROM seats s
JOIN rooms r ON s.room_id = r.id
WHERE s.id = $1
`

type GetSeatDetailByIDRow struct {
	ID         uuid.UUID
	RoomID     uuid.UUID
	RowLabel   string
	SeatNumber int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	RoomName   string
}

func (q *Queries) GetSeatDetailByID(ctx context.Context, id uuid.UUID) (GetSeatDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSeatDetailByID, id)
	var i GetSeatDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RowLabel,
		&i.SeatNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoomName,
	)
	return i, err
}

const updateSeat = `-- name: UpdateSeat :one
UPDATE seats
SET updated_at = NOW(), room_id = $2, row_label = $3, seat_number = $4
WHERE id = $1
RETURNING id, room_id, row_label, seat_number, created_at, updated_at
`

type UpdateSeatParams struct {
	ID         uuid.UUID
	RoomID     uuid.UUID
	RowLabel   string
	SeatNumber int32
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error) {
	row := q.db.QueryRowContext(ctx, updateSeat,
		arg.ID,
		arg.RoomID,
		arg.RowLabel,
		arg.SeatNumber,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RowLabel,
		&i.SeatNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
