# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
from typing import Optional
import uuid


@dataclasses.dataclass()
class EmailVerification:
    id: uuid.UUID
    user_id: uuid.UUID
    user_email: str
    code: str
    created_at: datetime.datetime
    expires_at: datetime.datetime


@dataclasses.dataclass()
class Genre:
    id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime
    name: str


@dataclasses.dataclass()
class Movie:
    id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime
    title: str
    slug: str
    description: Optional[str]
    runtime_minutes: Optional[int]
    release_date: Optional[datetime.date]
    poster_url: Optional[str]


@dataclasses.dataclass()
class MovieGenre:
    movie_id: uuid.UUID
    genre_id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class PwResetToken:
    hashed_token: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    user_id: uuid.UUID
    expires_at: datetime.datetime
    revoked_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class RefreshToken:
    token: str
    created_at: datetime.datetime
    updated_at: datetime.datetime
    user_id: uuid.UUID
    expires_at: datetime.datetime
    revoked_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Reservation:
    id: uuid.UUID
    user_id: uuid.UUID
    screening_id: uuid.UUID
    room_id: uuid.UUID
    seat_id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class Room:
    id: uuid.UUID
    name: str
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class Screening:
    id: uuid.UUID
    movie_id: uuid.UUID
    room_id: uuid.UUID
    start_time: datetime.datetime
    end_time: datetime.datetime
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class Seat:
    id: uuid.UUID
    room_id: uuid.UUID
    row_label: str
    seat_number: int
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class User:
    id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime
    email: str
    hashed_password: str
    role: str
    is_active: bool
