# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: movies.sql
import dataclasses
from typing import Iterator, Optional
import uuid

import sqlalchemy

from database import models


LOAD_MOVIES = """-- name: load_movies \\:many
SELECT id, title, description 
FROM movies
"""


@dataclasses.dataclass()
class LoadMoviesRow:
    id: uuid.UUID
    title: str
    description: Optional[str]


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def load_movies(self) -> Iterator[LoadMoviesRow]:
        result = self._conn.execute(sqlalchemy.text(LOAD_MOVIES))
        for row in result:
            yield LoadMoviesRow(
                id=row[0],
                title=row[1],
                description=row[2],
            )
